Abbreviation plugin
ckeditor/ckeditor5-tutorials-examples pull request #7
Opened 2024-04-10 10:43 UTC by gorzelinski

2024-04-10 13:00 UTC, illia-stv requested changes

2024-04-10 13:07 UTC, illia-stv approved these changes

2024-04-10 13:07 UTC, illia-stv commented on abbreviation-plugin/part-1/package.json
> +    "ckeditor5": "^41.3.0-alpha.4"
Leave comment to remember we need replace version with proper one. The same with others.

2024-04-11 08:42 UTC, illia-stv commented on abbreviation-plugin/part-2/public/vite.svg
Please remove public directories, the same in other parts.

2024-04-11 08:43 UTC, illia-stv commented on abbreviation-plugin/part-1/javascript.svg
Also remove all svg's generated by vite's CLI like this one.

2024-04-12 11:00 UTC, Witoso approved these changes
I just scanned but looks good 👍

2024-04-12 11:59 UTC, godai78 approved these changes
LGTM

2024-04-15 07:08 UTC, merged